services:
  storedb:
    image: postgres:14
    container_name: storedb
    ports:
      - "5432:5432"
    networks:
      - crypto-net
    volumes:
      - db-data-postgres-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  storeapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storeapp
    networks:
      - crypto-net
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - storedb
    environment:
      - POSTGRES_DB=store-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=storedb 
networks:
  crypto-net:
volumes:
  db-data-postgres-market:
  db-data-postgres-asset:



